blank_issues_enabled: true
contact_links:
  - name: Questions / Support
    url: https://github.com/JBSmith29/DragonsVault/discussions
    about: Please ask questions here if Discussions are enabled.
